version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: toolbox
    main: ./cmd/toolbox
    binary: toolbox
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/krubenok/toolbox/internal/cli.Version={{.Version}}
      - -X github.com/krubenok/toolbox/internal/cli.Commit={{.Commit}}
      - -X github.com/krubenok/toolbox/internal/cli.BuildDate={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

brews:
  - name: toolbox
    repository:
      owner: krubenok
      name: homebrew-tap
    directory: Formula
    homepage: "https://github.com/krubenok/toolbox"
    description: "AI-assisted software development tools"
    license: "MIT"
    test: |
      system "#{bin}/toolbox", "version"
